server:
  port: 8080

spring:
  application:
    name: payment-service-app
  datasource:  # объединяет в себе параметры подключения к БД
    url: jdbc:postgresql://localhost:5432/payment-db   # URL подключения к БД
    username: admin # Имя пользователя
    password: secret # Пароль
    driver-class-name: org.postgresql.Driver # класс jdbc драйвера
  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true # Показывать SQL-запросы в консоли
    properties:
      hibernate:
        format_sql: true # Форматировать SQL для читаемости
  liquibase:
    enabled: true
    change-log: classpath:db/changelog/db.changelog-master.yaml
  security:
    oauth2:
      resourceserver:
        jwt:
          issuer-uri: http://localhost:8085/realms/iprody-lms

  kafka:
    bootstrap-servers: localhost:9093

    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

    consumer:
      group-id: xpayment-adapter-result-consumers
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.springframework.kafka.support.serializer.JsonDeserializer
      auto-offset-reset: earliest # Откуда начинают читать новые consumers
      enable-auto-commit: false
      properties:
        spring.json.trusted.packages: "com.iprody.payment.service.app.async"
        spring.json.value.default.type: "com.iprody.payment.service.app.async.XPaymentAdapterResponseMessage"

    listener:
      ack-mode: manual
      concurrency: 1 # Количество consumers

# В разделе app.kafka.topics мы указали имена очередей для входящих и исходящих сообщений
app:
  kafka:
    topics:
      xpayment-adapter:
        request: xpayment-adapter.requests
        response: xpayment-adapter.responses

management:
  endpoints:
    web:
      exposure:
        include: health,info,liquibase,beans,metrics,env,loggers

logging:
  level:
    com.iprody.payment: DEBUG
    org.springframework.web: INFO
    org.springframework.data: INFO
    org.springframework.security: INFO
