name: Build Project for PR

on:
  pull_request:
    branches:
#      - 'main' # Запуск только при создании или обновлении pull request в ветку main
      - '**'    # Триггер на pull request в любую ветку

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Шаг 1: Клонируем код
    - name: Checkout code
      uses: actions/checkout@v4
    # Шаг 2: Устанавливаем JDK 21
    - name: Set up JDK 21
      uses: actions/setup-java@v4
      with:
        java-version: '21'
        distribution: 'temurin'
    # Шаг 3: Компиляция проекта (без тестов)
    - name: Compile with Maven
      run: mvn -B clean compile
    # Шаг 4: Запуск тестов отдельно
    - name: Run tests
      run: mvn -B test
    # Шаг 5: Запуск checkstyle
    - name: Run Checkstyle for payment-service-app
      working-directory: ./payment-service-app
      run: mvn -B checkstyle:check

